# ghc 8.10.7
resolver: lts-18.20

packages:
 - .

flags:
 xmobar:
   with_dbus: true
   with_threaded: true
   with_xrender: true

extra-deps:
 - netlink-1.1.1.0
 - libmpd-0.9.2.0
 - cairo-0.13.8.2
 - pango-0.13.8.2
 - glib-0.13.8.2
 - gtk2hs-buildtools-0.13.8.3
nix:
    packages:
      - alsaLib
      - pkgconfig
      - wirelesstools
      - xorg.libX11
      - xorg.libXext
      - xorg.libXft
      - xorg.libXpm
      - xorg.libXrandr
      - xorg.libXScrnSaver
      - zlib
